
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AppFooter': typeof import("../components/AppFooter.vue")['default']
    'AppHeader': typeof import("../components/AppHeader.vue")['default']
    'CatalogNew': typeof import("../components/CatalogNew.vue")['default']
    'EmailContact': typeof import("../components/EmailContact.vue")['default']
    'NewsBlock': typeof import("../components/NewsBlock.vue")['default']
    'OurBenefits': typeof import("../components/OurBenefits.vue")['default']
    'WelcomeBlock': typeof import("../components/WelcomeBlock.vue")['default']
    'WillBeSoon': typeof import("../components/WillBeSoon.vue")['default']
    'IconsBurger': typeof import("../components/icons/burger.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'UiButton': typeof import("../components/ui-kit/button/index")['Button']
    'UiForm': typeof import("../components/ui-kit/form/index")['Form']
    'UiFormField': typeof import("../components/ui-kit/form/index")['FormField']
    'UiFormItem': typeof import("../components/ui-kit/form/index")['FormItem']
    'UiFormLabel': typeof import("../components/ui-kit/form/index")['FormLabel']
    'UiFormControl': typeof import("../components/ui-kit/form/index")['FormControl']
    'UiFormMessage': typeof import("../components/ui-kit/form/index")['FormMessage']
    'UiFormDescription': typeof import("../components/ui-kit/form/index")['FormDescription']
    'UiFORMITEMINJECTIONKEY': typeof import("../components/ui-kit/form/index")['FORM_ITEM_INJECTION_KEY']
    'UiInput': typeof import("../components/ui-kit/input/index")['Input']
    'UiLabel': typeof import("../components/ui-kit/label/index")['Label']
    'UiToaster': typeof import("../components/ui-kit/toast/index")['Toaster']
    'UiToast': typeof import("../components/ui-kit/toast/index")['Toast']
    'UiToastViewport': typeof import("../components/ui-kit/toast/index")['ToastViewport']
    'UiToastAction': typeof import("../components/ui-kit/toast/index")['ToastAction']
    'UiToastClose': typeof import("../components/ui-kit/toast/index")['ToastClose']
    'UiToastTitle': typeof import("../components/ui-kit/toast/index")['ToastTitle']
    'UiToastDescription': typeof import("../components/ui-kit/toast/index")['ToastDescription']
    'UiToastProvider': typeof import("../components/ui-kit/toast/index")['ToastProvider']
    'NuxtIcon': typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
    'VeeField': typeof import("vee-validate")['Field']
    'VeeForm': typeof import("vee-validate")['Form']
    'VeeErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'VeeFieldArray': typeof import("vee-validate")['FieldArray']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAppFooter': typeof import("../components/AppFooter.vue")['default']
    'LazyAppHeader': typeof import("../components/AppHeader.vue")['default']
    'LazyCatalogNew': typeof import("../components/CatalogNew.vue")['default']
    'LazyEmailContact': typeof import("../components/EmailContact.vue")['default']
    'LazyNewsBlock': typeof import("../components/NewsBlock.vue")['default']
    'LazyOurBenefits': typeof import("../components/OurBenefits.vue")['default']
    'LazyWelcomeBlock': typeof import("../components/WelcomeBlock.vue")['default']
    'LazyWillBeSoon': typeof import("../components/WillBeSoon.vue")['default']
    'LazyIconsBurger': typeof import("../components/icons/burger.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyUiButton': typeof import("../components/ui-kit/button/index")['Button']
    'LazyUiForm': typeof import("../components/ui-kit/form/index")['Form']
    'LazyUiFormField': typeof import("../components/ui-kit/form/index")['FormField']
    'LazyUiFormItem': typeof import("../components/ui-kit/form/index")['FormItem']
    'LazyUiFormLabel': typeof import("../components/ui-kit/form/index")['FormLabel']
    'LazyUiFormControl': typeof import("../components/ui-kit/form/index")['FormControl']
    'LazyUiFormMessage': typeof import("../components/ui-kit/form/index")['FormMessage']
    'LazyUiFormDescription': typeof import("../components/ui-kit/form/index")['FormDescription']
    'LazyUiFORMITEMINJECTIONKEY': typeof import("../components/ui-kit/form/index")['FORM_ITEM_INJECTION_KEY']
    'LazyUiInput': typeof import("../components/ui-kit/input/index")['Input']
    'LazyUiLabel': typeof import("../components/ui-kit/label/index")['Label']
    'LazyUiToaster': typeof import("../components/ui-kit/toast/index")['Toaster']
    'LazyUiToast': typeof import("../components/ui-kit/toast/index")['Toast']
    'LazyUiToastViewport': typeof import("../components/ui-kit/toast/index")['ToastViewport']
    'LazyUiToastAction': typeof import("../components/ui-kit/toast/index")['ToastAction']
    'LazyUiToastClose': typeof import("../components/ui-kit/toast/index")['ToastClose']
    'LazyUiToastTitle': typeof import("../components/ui-kit/toast/index")['ToastTitle']
    'LazyUiToastDescription': typeof import("../components/ui-kit/toast/index")['ToastDescription']
    'LazyUiToastProvider': typeof import("../components/ui-kit/toast/index")['ToastProvider']
    'LazyNuxtIcon': typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
    'LazyVeeField': typeof import("vee-validate")['Field']
    'LazyVeeForm': typeof import("vee-validate")['Form']
    'LazyVeeErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'LazyVeeFieldArray': typeof import("vee-validate")['FieldArray']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AppFooter: typeof import("../components/AppFooter.vue")['default']
export const AppHeader: typeof import("../components/AppHeader.vue")['default']
export const CatalogNew: typeof import("../components/CatalogNew.vue")['default']
export const EmailContact: typeof import("../components/EmailContact.vue")['default']
export const NewsBlock: typeof import("../components/NewsBlock.vue")['default']
export const OurBenefits: typeof import("../components/OurBenefits.vue")['default']
export const WelcomeBlock: typeof import("../components/WelcomeBlock.vue")['default']
export const WillBeSoon: typeof import("../components/WillBeSoon.vue")['default']
export const IconsBurger: typeof import("../components/icons/burger.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const UiButton: typeof import("../components/ui-kit/button/index")['Button']
export const UiForm: typeof import("../components/ui-kit/form/index")['Form']
export const UiFormField: typeof import("../components/ui-kit/form/index")['FormField']
export const UiFormItem: typeof import("../components/ui-kit/form/index")['FormItem']
export const UiFormLabel: typeof import("../components/ui-kit/form/index")['FormLabel']
export const UiFormControl: typeof import("../components/ui-kit/form/index")['FormControl']
export const UiFormMessage: typeof import("../components/ui-kit/form/index")['FormMessage']
export const UiFormDescription: typeof import("../components/ui-kit/form/index")['FormDescription']
export const UiFORMITEMINJECTIONKEY: typeof import("../components/ui-kit/form/index")['FORM_ITEM_INJECTION_KEY']
export const UiInput: typeof import("../components/ui-kit/input/index")['Input']
export const UiLabel: typeof import("../components/ui-kit/label/index")['Label']
export const UiToaster: typeof import("../components/ui-kit/toast/index")['Toaster']
export const UiToast: typeof import("../components/ui-kit/toast/index")['Toast']
export const UiToastViewport: typeof import("../components/ui-kit/toast/index")['ToastViewport']
export const UiToastAction: typeof import("../components/ui-kit/toast/index")['ToastAction']
export const UiToastClose: typeof import("../components/ui-kit/toast/index")['ToastClose']
export const UiToastTitle: typeof import("../components/ui-kit/toast/index")['ToastTitle']
export const UiToastDescription: typeof import("../components/ui-kit/toast/index")['ToastDescription']
export const UiToastProvider: typeof import("../components/ui-kit/toast/index")['ToastProvider']
export const NuxtIcon: typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
export const VeeField: typeof import("vee-validate")['Field']
export const VeeForm: typeof import("vee-validate")['Form']
export const VeeErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const VeeFieldArray: typeof import("vee-validate")['FieldArray']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAppFooter: typeof import("../components/AppFooter.vue")['default']
export const LazyAppHeader: typeof import("../components/AppHeader.vue")['default']
export const LazyCatalogNew: typeof import("../components/CatalogNew.vue")['default']
export const LazyEmailContact: typeof import("../components/EmailContact.vue")['default']
export const LazyNewsBlock: typeof import("../components/NewsBlock.vue")['default']
export const LazyOurBenefits: typeof import("../components/OurBenefits.vue")['default']
export const LazyWelcomeBlock: typeof import("../components/WelcomeBlock.vue")['default']
export const LazyWillBeSoon: typeof import("../components/WillBeSoon.vue")['default']
export const LazyIconsBurger: typeof import("../components/icons/burger.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyUiButton: typeof import("../components/ui-kit/button/index")['Button']
export const LazyUiForm: typeof import("../components/ui-kit/form/index")['Form']
export const LazyUiFormField: typeof import("../components/ui-kit/form/index")['FormField']
export const LazyUiFormItem: typeof import("../components/ui-kit/form/index")['FormItem']
export const LazyUiFormLabel: typeof import("../components/ui-kit/form/index")['FormLabel']
export const LazyUiFormControl: typeof import("../components/ui-kit/form/index")['FormControl']
export const LazyUiFormMessage: typeof import("../components/ui-kit/form/index")['FormMessage']
export const LazyUiFormDescription: typeof import("../components/ui-kit/form/index")['FormDescription']
export const LazyUiFORMITEMINJECTIONKEY: typeof import("../components/ui-kit/form/index")['FORM_ITEM_INJECTION_KEY']
export const LazyUiInput: typeof import("../components/ui-kit/input/index")['Input']
export const LazyUiLabel: typeof import("../components/ui-kit/label/index")['Label']
export const LazyUiToaster: typeof import("../components/ui-kit/toast/index")['Toaster']
export const LazyUiToast: typeof import("../components/ui-kit/toast/index")['Toast']
export const LazyUiToastViewport: typeof import("../components/ui-kit/toast/index")['ToastViewport']
export const LazyUiToastAction: typeof import("../components/ui-kit/toast/index")['ToastAction']
export const LazyUiToastClose: typeof import("../components/ui-kit/toast/index")['ToastClose']
export const LazyUiToastTitle: typeof import("../components/ui-kit/toast/index")['ToastTitle']
export const LazyUiToastDescription: typeof import("../components/ui-kit/toast/index")['ToastDescription']
export const LazyUiToastProvider: typeof import("../components/ui-kit/toast/index")['ToastProvider']
export const LazyNuxtIcon: typeof import("../node_modules/nuxt-svgo/dist/runtime/components/nuxt-icon.vue")['default']
export const LazyVeeField: typeof import("vee-validate")['Field']
export const LazyVeeForm: typeof import("vee-validate")['Form']
export const LazyVeeErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const LazyVeeFieldArray: typeof import("vee-validate")['FieldArray']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
