// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/16/2024, 9:44:05 AM
const configMerger = require("/Users/o2/Desktop/Projects/TestNuxt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/o2/Desktop/Projects/TestNuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/o2/Desktop/Projects/TestNuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/o2/Desktop/Projects/TestNuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/o2/Desktop/Projects/TestNuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/o2/Desktop/Projects/TestNuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/o2/Desktop/Projects/TestNuxt/plugins/**/*.{js,ts,mjs}","/Users/o2/Desktop/Projects/TestNuxt/composables/**/*.{js,ts,mjs}","/Users/o2/Desktop/Projects/TestNuxt/utils/**/*.{js,ts,mjs}","/Users/o2/Desktop/Projects/TestNuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/o2/Desktop/Projects/TestNuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/o2/Desktop/Projects/TestNuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
